### PR TITLE
[UPD] costarica: Update to fix traceback after Hacienda's hack - I#18515

### PR DESCRIPTION
**Pull request by ebirbe**
```bash
$ git log 565de2d..HEAD --oneline
```
```git
fcb6e43 [FIX] l10n_cr_edi: avoid traceback when the connection with hacienda is not successful
43685c1 [IMP] l10n_cr_hr_payroll: Welcome commisions rule
2cdac25 [ADD] l10n_cr_edi: Set default type for Credit notes with out use_document journal
9d5be50 [IMP] l10n_cr_hr_payroll: Improve report to be compatible
49a9c77 [FIX] l10n_cr_edi: Fix state migration script when first installation
105d71f [FIX] l10n_cr_edi: Unify the _reverse_moves method which is duplicated
8629416 [IMP] l10n_cr_edi: Better test for sequence in invoices
dddca18 [IMP] l10n_cr_edi: Welcome test with error on sequence
d61b031 [IMP] l10n_cr_hr_payroll: Correct account code for demo data
c9ea7f0 [IMP] l10n_cr_hr_payroll: Improved replaces on PDF report
0612469 [IMP] l10n_cr_hr_payroll: Code for work entries updated
a901e74 [IMP] costarica: Translation for credit note fixed
```

This update is required after the Hacienda Ministry's hack that leave Odoo giving the next traceback uploading the required attachments into the SO:

```python
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/odoo/src/odoo/odoo/http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 361, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/http.py", line 349, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 914, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 533, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1394, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1386, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 399, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 386, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/models.py", line 6264, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/home/odoo/src/odoo/odoo/models.py", line 6006, in _onchange_eval
    method_res = method(self)
  File "/home/odoo/src/user/costarica/l10n_cr_edi/models/res_partner.py", line 67, in _onchange_vat
    message, response = self.sugef_get(service="identificacion")
  File "/home/odoo/src/user/costarica/l10n_cr_edi/models/res_partner.py", line 90, in sugef_get
    req = requests.get("%s?%s=%s" % (url, service, self.vat), headers)
  File "/usr/local/lib/python3.6/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 641, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/odoo/http.py", line 317, in _handle_exception
    raise exception.with_traceback(None) from new_cause
requests.exceptions.ConnectionError: ('Connection aborted.', OSError("(104, 'ECONNRESET')",))
```

### CODE REVIEW

**Comment by hugho-ad** [comment]
your commit said that because the Haciendas hack, now a traceback comes up, which traceback?

**Comment by hugho-ad** [comment]
I already see it

fcb6e43 [FIX] l10n_cr_edi: avoid traceback when the connection with hacienda is not successful


Pls, elaborate more

**Comment by ebirbe** [comment]
Thanks, I've updated the title and the description.

**Comment by ebirbe** [comment]
@hugho-ad customer approved this changes functionally and @allanpa88 approved too.

This is ready for merge since 5:30pm Costa Rica time. I have scheduled for you the this merge a in your calendar at 6pm CR time.

**Pull request merged**
